export const ROUTES = Object.freeze({
  home: "/",
  login: "/login",
  signup: "/signup",
  profile: "/profile",
  inspection: "/inspection",
  histories: "/histories",
  reinspections: "/reinspections",
  analytics: "/analytics",
  boards: "/boards",
  hokeytoon: "/hokeytoon",
  boardWrite: "/boards/write",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminBoards: "/admin/boards",
  adminComments: "/admin/comments",
  adminActivity: "/admin/activity",
  adminDetections: "/admin/ai/detections",
  adminAiData: "/admin/ai/data",
  adminAiModels: "/admin/ai/models",
  adminAiRecommendationSchedule: "/admin/ai/recommendation-schedule",
  adminWasteTypes: "/admin/ai/wastes",
  adminSettings: "/admin/settings",
  adminForbiddenWords: "/admin/settings/forbidden-words",
  adminMenus: "/admin/settings/menus",

  // masterData 경로
  masterData: "/master-data",
  masterDataWastes: "/master-data/wastes",
  masterDataLocations: "/master-data/locations",
});
