"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import ErrorMessage from "@/components/common/ErrorMessage";
import { historyService } from "@/services/historyService";
import { getApiErrorMessage } from "@/services/apiClient";
import "../reinspections.css";

const COLORS=["#36a2eb","#ff6384","#4bc0c0","#ff9f40","#9966ff","#57a773"],clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
const percent=value=>value==null?"-":`${(Number(value)*100).toFixed(1)}%`;
export default function ReinspectionLabelEditor(){
 const {id}=useParams(),router=useRouter(),inspectionId=Number(id),canvasRef=useRef(null),gestureRef=useRef(null),nextId=useRef(-1);
 const [detail,setDetail]=useState(null),[classes,setClasses]=useState([]),[imageUrl,setImageUrl]=useState(""),[boxes,setBoxes]=useState([]),[selected,setSelected]=useState(null),[mode,setMode]=useState("select"),[deletedIds,setDeletedIds]=useState([]),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [item,types,blob]=await Promise.all([historyService.getReinspectionDetail(inspectionId),historyService.getReinspectionClasses(),historyService.getHistoryImage(inspectionId,"ORIGINAL")]);setDetail(item);setClasses(types);setBoxes(item.detections.map((d,i)=>({id:d.id,className:d.className,originalClassName:d.originalClassName,confidence:d.confidence,modified:Boolean(d.modified),manuallyAdded:Boolean(d.manuallyAdded),bbox:[d.bboxX,d.bboxY,d.bboxWidth,d.bboxHeight].map(Number),color:COLORS[i%COLORS.length]})));setImageUrl(URL.createObjectURL(blob));}catch(e){setError(getApiErrorMessage(e,"라벨링 데이터를 불러오지 못했습니다."));}},[inspectionId]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);useEffect(()=>()=>{if(imageUrl)URL.revokeObjectURL(imageUrl);},[imageUrl]);
 const point=e=>{const r=canvasRef.current.getBoundingClientRect();return[clamp((e.clientX-r.left)/r.width),clamp((e.clientY-r.top)/r.height)]},patch=(id,p)=>setBoxes(v=>v.map(b=>b.id===id?{...b,...p,modified:true}:b));
 const down=e=>{if(e.button!==0||mode!=="draw")return;const[x,y]=point(e),id=nextId.current--;gestureRef.current={kind:"draw",start:[x,y],id};setBoxes(v=>[...v,{id,className:classes[0]?.name||"Unknown",originalClassName:null,confidence:null,modified:true,manuallyAdded:true,bbox:[x,y,.001,.001],color:COLORS[v.length%COLORS.length]}]);setSelected(id);e.currentTarget.setPointerCapture(e.pointerId)};
 const start=(e,b,kind)=>{if(mode!=="select")return;e.stopPropagation();gestureRef.current={kind,id:b.id,start:point(e),original:[...b.bbox]};setSelected(b.id);canvasRef.current.setPointerCapture(e.pointerId)};
 const move=e=>{const g=gestureRef.current;if(!g)return;const[x,y]=point(e);if(g.kind==="draw"){patch(g.id,{bbox:[Math.min(g.start[0],x),Math.min(g.start[1],y),Math.max(.001,Math.abs(x-g.start[0])),Math.max(.001,Math.abs(y-g.start[1]))]});return}const dx=x-g.start[0],dy=y-g.start[1],b=g.original;if(g.kind==="move")patch(g.id,{bbox:[clamp(b[0]+dx,0,1-b[2]),clamp(b[1]+dy,0,1-b[3]),b[2],b[3]]});else patch(g.id,{bbox:[b[0],b[1],clamp(b[2]+dx,.005,1-b[0]),clamp(b[3]+dy,.005,1-b[1])]})};
 const up=()=>{gestureRef.current=null;if(mode==="draw")setMode("select")},remove=()=>{const b=boxes.find(v=>v.id===selected);if(!b)return;if(b.id>0)setDeletedIds(v=>[...v,b.id]);setBoxes(v=>v.filter(x=>x.id!==selected));setSelected(null)};
 const save=async()=>{setSaving(true);try{await historyService.saveReinspectionAnnotations(inspectionId,{boxes:boxes.map(b=>({id:b.id>0?b.id:null,className:b.className,bbox:b.bbox})),deletedIds});router.push("/reinspections");}catch(e){setError(getApiErrorMessage(e,"라벨 저장에 실패했습니다."));}finally{setSaving(false)}};const current=boxes.find(b=>b.id===selected),aiBoxes=boxes.filter(b=>!b.manuallyAdded&&b.confidence!=null),averageConfidence=aiBoxes.length?aiBoxes.reduce((sum,b)=>sum+Number(b.confidence),0)/aiBoxes.length:null;
 return <main className="page-shell reinspection-editor"><header className="reinspection-head"><div><span>MANUAL LABELING</span><h1>{detail?.title||"수동 라벨링"}</h1><p>Bounding Box를 직접 추가하거나 위치와 클래스를 수정합니다.</p></div><Link href="/reinspections">목록으로 돌아가기</Link></header><ErrorMessage message={error}/>{detail&&<section className="reinspection-model-summary"><div><span>사용 모델</span><strong>{detail.modelDisplayName||detail.modelName||"모델 정보 없음"}</strong><small>{detail.modelVersion||"버전 정보 없음"}</small></div><div><span>이미지 평균 신뢰도</span><strong>{percent(averageConfidence)}</strong><small>AI 최초 탐지 {aiBoxes.length}개 기준</small></div><div><span>모델 성능</span><strong>{percent(detail.modelMap50)}</strong><small>mAP50 · mAP50-95 {percent(detail.modelMap50_95)}</small></div><div><span>학습 설정</span><strong>{detail.modelBaseName||"-"}</strong><small>{detail.modelOptimizer||"-"} · {detail.modelEpochs??"-"} epochs · {detail.modelImageSize??"-"}px</small></div>{detail.modelExternalId&&<Link className="reinspection-model-link" href={`/admin/ai/models/${detail.modelExternalId}`}>모델 상세 보기</Link>}</section>}<section className="reinspection-editor-toolbar"><div><button className={mode==="select"?"active":""} onClick={()=>setMode("select")}>선택·이동</button><button className={mode==="draw"?"active":""} onClick={()=>setMode("draw")}>박스 추가</button><button disabled={!selected} onClick={remove}>선택 삭제</button></div><span>객체 {boxes.length}개</span><button className="btn btn-primary" disabled={saving||!detail} onClick={save}>{saving?"저장 중...":"라벨 저장"}</button></section><div className="reinspection-editor-grid"><section className="reinspection-canvas-wrap"><div ref={canvasRef} className={`reinspection-canvas mode-${mode}`} style={imageUrl?{backgroundImage:`url("${imageUrl}")`}:undefined} onPointerDown={down} onPointerMove={move} onPointerUp={up}>{boxes.map(b=><i key={b.id} className={`edit-box${selected===b.id?" selected":""}`} style={{left:`${b.bbox[0]*100}%`,top:`${b.bbox[1]*100}%`,width:`${b.bbox[2]*100}%`,height:`${b.bbox[3]*100}%`,borderColor:b.color}} onPointerDown={e=>start(e,b,"move")}><b style={{background:b.color}}>{b.className}</b>{selected===b.id&&<em onPointerDown={e=>start(e,b,"resize")}/>}</i>)}</div></section><aside className="reinspection-properties"><h2>객체 목록</h2>{boxes.map(b=><button key={b.id} className={selected===b.id?"active":""} onClick={()=>setSelected(b.id)}><span>{b.className}{b.modified&&<em>수정됨</em>}</span><small>{b.manuallyAdded?"수동 추가":`AI 신뢰도 ${percent(b.confidence)}`}{b.originalClassName&&b.originalClassName!==b.className?` · ${b.originalClassName}에서 변경`:""}</small></button>)}{current&&<label><span>폐기물 유형</span><select value={current.className} onChange={e=>patch(current.id,{className:e.target.value})}>{classes.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label>}</aside></div></main>;
}