"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { adminService } from "@/services/adminService";
import { getApiErrorMessage } from "@/services/apiClient";
import ErrorMessage from "@/components/common/ErrorMessage";

const formatDate = (v) => v ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short" }).format(new Date(`${v}Z`)) : "-";

export default function ForbiddenWordsPage() {
  const [words,setWords]=useState([]); const [flags,setFlags]=useState(null); const [word,setWord]=useState("");
  const [status,setStatus]=useState("OPEN"); const [type,setType]=useState(""); const [page,setPage]=useState(1);
  const [loading,setLoading]=useState(true); const [working,setWorking]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setError("");try{const [w,f]=await Promise.all([adminService.getForbiddenWords(),adminService.getModerationFlags({page,pageSize:20,status:status||undefined,type:type||undefined})]);setWords(w);setFlags(f);}catch(e){setError(getApiErrorMessage(e,"금칙어 정보를 불러오지 못했습니다."));}finally{setLoading(false);}},[page,status,type]);
  useEffect(()=>{const t=window.setTimeout(()=>load(),0);return()=>window.clearTimeout(t);},[load]);
  const add=async(e)=>{e.preventDefault();if(word.trim().length<2){setError("금칙어는 2자 이상 입력해 주세요.");return;}setWorking("add");setError("");try{await adminService.createForbiddenWord(word.trim());setWord("");setNotice("금칙어를 등록하고 기존 콘텐츠를 재검사했습니다.");await load();}catch(x){setError(getApiErrorMessage(x,"금칙어를 등록하지 못했습니다."));}finally{setWorking("");}};
  const toggle=async(item)=>{setWorking(`word-${item.id}`);try{await adminService.toggleForbiddenWord(item.id,!item.isActive);await load();}catch(e){setError(getApiErrorMessage(e,"상태를 변경하지 못했습니다."));}finally{setWorking("");}};
  const remove=async(item)=>{if(!window.confirm(`“${item.word}” 금칙어를 삭제할까요? 관련 탐지 기록도 삭제됩니다.`))return;setWorking(`word-${item.id}`);try{await adminService.deleteForbiddenWord(item.id);await load();}catch(e){setError(getApiErrorMessage(e,"금칙어를 삭제하지 못했습니다."));}finally{setWorking("");}};
  const resolve=async(item,next)=>{const note=window.prompt(next==="RESOLVED"?"처리 메모를 입력하세요.":"오탐 사유를 입력하세요.","");if(note===null)return;setWorking(`flag-${item.id}`);try{await adminService.resolveModerationFlag(item.id,next,note);setNotice("탐지 결과를 처리했습니다.");await load();}catch(e){setError(getApiErrorMessage(e,"탐지 결과를 처리하지 못했습니다."));}finally{setWorking("");}};
  return <div className="admin-page forbidden-page"><header className="admin-page-head"><div><span className="admin-kicker">CONTENT SAFETY</span><h1>금칙어 관리</h1><p>게시글과 댓글을 자동 검사하고 탐지된 콘텐츠를 관리자에게 표시합니다.</p></div></header><ErrorMessage message={error}/>{notice&&<p className="admin-success-message">{notice}</p>}
    <div className="forbidden-layout"><section className="admin-panel"><div className="admin-toolbar"><div><h2>금칙어 설정</h2><p>추가 즉시 기존 콘텐츠도 재검사합니다.</p></div></div><form className="forbidden-add" onSubmit={add}><input value={word} maxLength="100" onChange={e=>setWord(e.target.value)} placeholder="새 금칙어 입력"/><button disabled={working==="add"}>등록</button></form><div className="forbidden-word-list">{words.map(item=><div key={item.id}><span><strong>{item.word}</strong><small>미처리 탐지 {item.openCount}건 · {item.createdByName||"관리자"}</small></span><label><input type="checkbox" checked={Boolean(item.isActive)} disabled={working===`word-${item.id}`} onChange={()=>toggle(item)}/><i>{item.isActive?"사용":"중지"}</i></label><button onClick={()=>remove(item)} disabled={working===`word-${item.id}`}>삭제</button></div>)}{!words.length&&!loading&&<p className="activity-empty">등록된 금칙어가 없습니다.</p>}</div></section>
    <section className="admin-panel forbidden-flags"><div className="admin-toolbar"><div><h2>탐지된 콘텐츠</h2><p>{flags?`총 ${flags.totalItems.toLocaleString()}건`:"탐지 결과를 조회합니다."}</p></div><div className="forbidden-filters"><select value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="">전체 유형</option><option value="BOARD">게시글</option><option value="COMMENT">댓글</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="OPEN">미처리</option><option value="RESOLVED">처리 완료</option><option value="DISMISSED">오탐</option><option value="">전체 상태</option></select></div></div>{loading?<div className="admin-data-loading"><span className="admin-spinner"/>불러오는 중...</div>:<div className="forbidden-flag-list">{(flags?.items||[]).map(item=><article key={item.id}><div className="forbidden-flag-head"><span className="forbidden-match">{item.word}</span><small>{item.contentType==="BOARD"?"게시글":"댓글"} · {formatDate(item.detectedAt)}</small></div><h3>{item.contentTitle||`콘텐츠 #${item.contentId}`}</h3><p>{item.excerpt}</p><footer><span>{item.authorName||"알 수 없음"}</span><div>{item.contentType==="BOARD"&&<Link href={`/boards/${item.contentId}`} target="_blank">원문 보기</Link>}{item.status==="OPEN"&&<><button disabled={working===`flag-${item.id}`} onClick={()=>resolve(item,"DISMISSED")}>오탐</button><button className="resolve" disabled={working===`flag-${item.id}`} onClick={()=>resolve(item,"RESOLVED")}>처리 완료</button></>}</div></footer></article>)}{flags&&!flags.items.length&&<p className="activity-empty">조건에 맞는 탐지 결과가 없습니다.</p>}</div>}{flags&&flags.totalPages>1&&<nav className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page} / {flags.totalPages}</span><button disabled={page>=flags.totalPages} onClick={()=>setPage(p=>p+1)}>다음</button></nav>}</section></div></div>;
}
